name: Windows Release

on: [push, pull_request]

env:
  QT_VERSION: 5.15.2

permissions:
  contents: write

jobs:
  build:
    runs-on: windows-latest

    steps:
    # 1. Checkout
    - name: Checkout
      uses: actions/checkout@v4
      with:
        submodules: recursive

    # 2. Python (for aqt)
    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'

    # 3. setup Qt (MinGW)
    - name: Install Qt
      uses: jurplel/install-qt-action@v3
      with:
        version: ${{ env.QT_VERSION }}
        arch: win64_mingw81
        
    - name: Install MinGW
      run: |
        choco install mingw -y        

    # 4. Build (Ninja + MinGW from Qt)
    - name: Build project
      shell: bash
      run: |
        mkdir build
        cd build

        QT_PATH="$Qt/${{ env.QT_VERSION }}/mingw81_64"

        export PATH="$QT_PATH/bin:$PATH"

        cmake .. -G Ninja \
          -DCMAKE_BUILD_TYPE=Release \
          -DCMAKE_PREFIX_PATH="$QT_PATH/lib/cmake" \
          -DCMAKE_C_COMPILER=gcc \
          -DCMAKE_CXX_COMPILER=g++

        ninja

    # 5. Deploy (Qt + plugins + MinGW runtime)
    - name: Deploy
      shell: bash
      run: |
        QT_PATH="${Qt5_Dir}"
        QT_ROOT="$(dirname "$(dirname "$QT_PATH")")"

        # Автоматически находим mingw папку
        MINGW_PATH=$(ls -d "$QT_ROOT"/Tools/mingw*/bin | head -n 1)

        echo "QT_PATH=$QT_PATH"
        echo "QT_ROOT=$QT_ROOT"
        echo "MINGW_PATH=$MINGW_PATH"

        mkdir -p release_dist
        cp build/ComPortEx_G.exe release_dist/

        # Qt deploy (full path)
        "$QT_PATH/bin/windeployqt.exe" \
          --release \
          --no-translations \
          --dir release_dist \
          release_dist/ComPortEx_G.exe

        # MinGW runtime (necessary)
        cp "$MINGW_PATH/libgcc_s_seh-1.dll" release_dist/
        cp "$MINGW_PATH/libstdc++-6.dll" release_dist/
        cp "$MINGW_PATH/libwinpthread-1.dll" release_dist/

    # 6. make archive
    - name: Zip Result
      shell: pwsh
      run: |
        Compress-Archive -Path release_dist\* -DestinationPath "App_${{ github.sha }}.zip"

    # 7. Artifact
    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: windows-build
        path: "*.zip"

    # 8. Release
    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        tag_name: latest
        name: "Latest Build"
        prerelease: true
        files: "*.zip"
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}		  
